services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - nexa-tracker:/var/lib/mysql
  backend:
      image: node:lts-stretch-slim
      restart: always
      env_file:
        - .env_db
        - .env_backend
volumes:
  nexa-tracker:
